### ISSUE TITLE
circles for molecules seem to be too low on the screen

### ISSUE THREAD

**Issue by juancarlosfarah** [graasp/graasp-app-radiation-absorption#39]
I would try to center them.

![image](https://user-images.githubusercontent.com/1707188/116519092-59040900-a8d1-11eb-8bcb-a1edbb51e134.png)

**Comment by hagoptaminian** [comment]
Good observation. Was aware of this issue. Some elaboration:

- The molecule containers need to be placed at half-period increments from the bottom of the screen (where _period_ is the period of the sine curve/radiation line), so that when they are struck by the radiation, they begin their oscillation in their original inactive position (noting that every half-period, the sine curve is back at 0). Otherwise we get an effect like this:

https://user-images.githubusercontent.com/19311953/116551009-be6af080-a8f7-11eb-9851-2a26c069986d.mov

- The teachers had commented that the containers were too high, making it hard to observe the re-emission effect. Originally placed at 192π (= 1.5 periods) from the bottom, the next possible position satisfying the constraint above was 128π (= 1 period), which is where they were placed.

- The solution is: Place the containers at 1, 1.5, or 2 periods from the bottom depending on screen height.
